In [ ]:
import numpy as np
list1 = [6,3,4,5,2] #1 dimentional array
a  = np.array(list1)

In [ ]:
a

array([6, 3, 4, 5, 2])

In [ ]:
type(a)

numpy.ndarray

In [ ]:
a.shape

(5,)

In [ ]:
a.min()

2

In [ ]:
a.max()

6

In [ ]:
a.argmax()  #index of maximum value

0

In [ ]:
a.argmin()

4

In [ ]:
list2 = [[8,9,8,0],[2,3,9,7]]
b = np.array(list2)


In [ ]:
b     #2 dimentinal array

array([[8, 9, 8, 0],
       [2, 3, 9, 7]])

In [ ]:
b.argmax()

1

In [ ]:
b.ndim

2

In [ ]:
a.ndim

1

In [ ]:
list3 = [[5,6,7,8],[5,7,3,4],[1,3,4,5]]
c = np.array(list3)

In [ ]:
c

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
c.ndim

2

In [ ]:
c.shape

(3, 4)

# indexing and slicing?

In [ ]:
a[2] #indexing

4

In [ ]:
b[1]

array([2, 3, 9, 7])

In [ ]:
c[2]

array([ 9, 10, 11, 12])

In [ ]:
c[:,1:3] #slicing , rows, columns

array([[ 2,  3],
       [ 6,  7],
       [10, 11]])

## functions

In [ ]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [ ]:
np.ones(5)*6

array([6., 6., 6., 6., 6.])

In [ ]:
np.arange(1, 11, 2)

array([1, 3, 5, 7, 9])

In [ ]:
np.linspace(0,10,20) #linearly spaced values

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [ ]:
np.random.rand(10) #0 and 1

array([0.37073492, 0.73679258, 0.6758592 , 0.21003229, 0.93902071,
       0.52552425, 0.30603684, 0.62842117, 0.64512268, 0.88023924])

In [ ]:
b = np.random.randint(1,100,24)

In [ ]:
b

array([81, 21, 62,  6, 49, 70, 62,  5, 93, 97, 82, 87, 15, 22, 26, 22,  8,
       73, 12, 70, 77, 85,  9, 79])

In [ ]:
np.sort(np.random.randint(1,100,24))

array([ 5,  7,  7,  9, 11, 19, 21, 22, 27, 30, 32, 35, 37, 39, 51, 52, 65,
       66, 66, 69, 74, 90, 91, 98])

In [ ]:
b.reshape(6,4)

array([[81, 21, 62,  6],
       [49, 70, 62,  5],
       [93, 97, 82, 87],
       [15, 22, 26, 22],
       [ 8, 73, 12, 70],
       [77, 85,  9, 79]])